DROP TABLE [ABAN_DER_ADOS].[MaterialxTarea]

DROP TABLE [ABAN_DER_ADOS].[TareaxOrden]

DROP TABLE [ABAN_DER_ADOS].[PaquetexViaje]

DROP TABLE [ABAN_DER_ADOS].OrdenTrabajo
DROP TABLE [ABAN_DER_ADOS].EstadoOT
DROP TABLE [ABAN_DER_ADOS].Mecanico
DROP TABLE [ABAN_DER_ADOS].Material
DROP TABLE [ABAN_DER_ADOS].Viaje
DROP TABLE [ABAN_DER_ADOS].TipoPaquete
DROP TABLE [ABAN_DER_ADOS].Tarea
DROP TABLE [ABAN_DER_ADOS].Recorrido
DROP TABLE [ABAN_DER_ADOS].Taller
DROP TABLE [ABAN_DER_ADOS].TipoTarea
DROP TABLE [ABAN_DER_ADOS].Camion
DROP TABLE [ABAN_DER_ADOS].CHOFEr
DROP TABLE [ABAN_DER_ADOS].Ciudad
DROP TABLE [ABAN_DER_ADOS].MARCA
DROP TABLE [ABAN_DER_ADOS].ModeloCamion

DROP PROCEDURE migrar
DROP PROCEDURE crear_tablas
